/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yml_minla_jnitest_jnipack_JniTest */

#ifndef _Included_yml_minla_jnitest_jnipack_JniTest
#define _Included_yml_minla_jnitest_jnipack_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yml_minla_jnitest_jnipack_JniTest
 * Method:    getJniLibraryName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yml_minla_jnitest_jnipack_JniTest_getJniLibraryName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
